/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Lumina.proyectolumina.gui.vistasClientUser;

import java.awt.Image;
import java.awt.TextArea;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JTextField;

/**
 *
 * @author USUARIO
 */
public class vistaContratarServicio2 extends javax.swing.JFrame {

    /**
     * Creates new form vistaContratarServicio2
     */
    public vistaContratarServicio2() {
        initComponents();


        ImageIcon iconLumina1 = new ImageIcon("src/main/java/com/Lumina/proyectolumina/gui/recursos multimedia/logo lumina blanco (2).png");
        Icon icon1 = new ImageIcon(iconLumina1.getImage().getScaledInstance(lblIconoLumina.getWidth(), lblIconoLumina.getHeight(), Image.SCALE_SMOOTH));
        lblIconoLumina.setIcon(icon1);

        ImageIcon imagenFondo = new ImageIcon("src/main/java/com/Lumina/proyectolumina/gui/recursos multimedia/fondo.jpg");
        Icon icon2 = new ImageIcon(imagenFondo.getImage().getScaledInstance(jPanelFondo.getWidth(), jPanelFondo.getHeight(), Image.SCALE_SMOOTH));
        jPanelFondo.setIcon(icon2);

        ImageIcon degradadoFondo = new ImageIcon("src/main/java/com/Lumina/proyectolumina/gui/recursos multimedia/textura banner.png");
        Icon icon3 = new ImageIcon(degradadoFondo.getImage().getScaledInstance(lblDegradado.getWidth(), lblDegradado.getHeight(), Image.SCALE_SMOOTH));
        lblDegradado.setIcon(icon3);

        ImageIcon iconoPerfil = new ImageIcon("src/main/java/com/Lumina/proyectolumina/gui/recursos multimedia/icono perfil.png");
        Icon icon4 = new ImageIcon(iconoPerfil.getImage().getScaledInstance(lblPerfilUsu.getWidth(), lblPerfilUsu.getHeight(), Image.SCALE_SMOOTH));
        lblPerfilUsu.setIcon(icon4);
    }

    public JButton getBtnRegresar() {
        return btnRegresar;
    }

    public JMenuItem getJmiCerrarSesion() {
        return jmiCerrarSesion;
    }

    public JMenuItem getJmiEditarPerfil() {
        return jmiEditarPerfil;
    }

    public JLabel getLblNombreUsu() {
        return lblNombreUsu;
    }

    public JButton getBtnPaso3() {
        return btnPaso3;
    }

    public JComboBox<String> getCbTdocumento() {
        return cbTdocumento;
    }

    public JComboBox<String> getCb_tPago() {
        return cb_tPago;
    }


    public JLabel getLblCategoriaSelec() {
        return lblCategoriaSelec;
    }

    public JLabel getLblServicioSelec() {
        return lblServicioSelec;
    }

    public TextArea getTxtAreaDescripcionServicio() {
        return txtAreaDescripcionServicio;
    }

    public JTextField getTxtCorreo() {
        return txtCorreo;
    }

    public JTextField getTxtDireccion() {
        return txtDireccion;
    }

    public JTextField getTxtNombre() {
        return txtNombre;
    }

    public JTextField getTxtNumDocumento() {
        return txtNumDocumento;
    }

    public JTextField getTxtTelefono() {
        return txtTelefono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpmAcionesUsuario = new javax.swing.JPopupMenu();
        jmiEditarPerfil = new javax.swing.JMenuItem();
        jmiCerrarSesion = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        btnPaso3 = new javax.swing.JButton();
        txtAreaDescripcionServicio = new java.awt.TextArea();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cbTdocumento = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNumDocumento = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cb_tPago = new javax.swing.JComboBox<>();
        txtDireccion = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        lblCategoriaSelec = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblServicioSelec = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblPerfilUsu = new javax.swing.JLabel();
        lblNombreUsu = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblIconoLumina = new javax.swing.JLabel();
        lblDegradado = new javax.swing.JLabel();
        jPanelFondo = new javax.swing.JLabel();

        jmiEditarPerfil.setFont(new java.awt.Font("Mulish", 0, 12)); // NOI18N
        jmiEditarPerfil.setText("Editar perfil");
        jpmAcionesUsuario.add(jmiEditarPerfil);

        jmiCerrarSesion.setFont(new java.awt.Font("Mulish", 0, 12)); // NOI18N
        jmiCerrarSesion.setText("Cerrar sesion");
        jpmAcionesUsuario.add(jmiCerrarSesion);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Mulish Black", 3, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(2, 31, 89));
        jLabel16.setText("PASO 2/3");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        btnRegresar.setBackground(new java.awt.Color(3, 90, 167));
        btnRegresar.setFont(new java.awt.Font("Mulish ExtraBold", 0, 18)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 120, -1));

        btnPaso3.setBackground(new java.awt.Color(4, 49, 140));
        btnPaso3.setFont(new java.awt.Font("Mulish ExtraBold", 0, 18)); // NOI18N
        btnPaso3.setForeground(new java.awt.Color(255, 255, 255));
        btnPaso3.setText("Siguiente");
        btnPaso3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaso3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnPaso3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 120, -1));
        jPanel1.add(txtAreaDescripcionServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 150, 60));

        jLabel15.setFont(new java.awt.Font("Mulish SemiBold", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(2, 31, 89));
        jLabel15.setText("Descripcion del servicio");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Mulish SemiBold", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(2, 31, 89));
        jLabel7.setText("Nombre completo ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        txtNombre.setEditable(false);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 160, -1));

        jLabel8.setFont(new java.awt.Font("Mulish SemiBold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(2, 31, 89));
        jLabel8.setText("Tipo de documento");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, -1, -1));

        cbTdocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "Cedula de ciudadania", "Cedula de extranjeria", "Pasaporte" }));
        cbTdocumento.setEnabled(false);
        jPanel1.add(cbTdocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, -1, -1));

        jLabel9.setFont(new java.awt.Font("Mulish SemiBold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(2, 31, 89));
        jLabel9.setText("Correo electronico");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, -1, -1));

        txtCorreo.setEditable(false);
        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 160, -1));

        jLabel11.setFont(new java.awt.Font("Mulish SemiBold", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(2, 31, 89));
        jLabel11.setText("Numero de documento");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, -1, -1));

        txtNumDocumento.setEditable(false);
        txtNumDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumDocumentoActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 150, -1));

        jLabel12.setFont(new java.awt.Font("Mulish SemiBold", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(2, 31, 89));
        jLabel12.setText("Telefono");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, -1, -1));

        txtTelefono.setEditable(false);
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 160, -1));

        jLabel13.setFont(new java.awt.Font("Mulish SemiBold", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(2, 31, 89));
        jLabel13.setText("Metodo de pago");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, -1, -1));

        cb_tPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "Tarjeta de debito / credito", "Transferencia bancaria", "Pago en efectivo" }));
        cb_tPago.setEnabled(false);
        jPanel1.add(cb_tPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 160, -1));

        txtDireccion.setEditable(false);
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        jPanel1.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 150, -1));

        jLabel14.setFont(new java.awt.Font("Mulish SemiBold", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(2, 31, 89));
        jLabel14.setText("Direccion");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        lblCategoriaSelec.setFont(new java.awt.Font("Mulish Light", 0, 12)); // NOI18N
        lblCategoriaSelec.setForeground(new java.awt.Color(34, 52, 64));
        lblCategoriaSelec.setText("[Nombre de la categoria seleccionada]");
        jPanel1.add(lblCategoriaSelec, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Mulish Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(34, 52, 64));
        jLabel3.setText("CATEGORIA SELECCIONADA:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jLabel10.setFont(new java.awt.Font("Mulish Black", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(2, 31, 89));
        jLabel10.setText("Informacion de contacto");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        lblServicioSelec.setFont(new java.awt.Font("Mulish Light", 0, 12)); // NOI18N
        lblServicioSelec.setForeground(new java.awt.Color(34, 52, 64));
        lblServicioSelec.setText("[Nombre del servicio seleccionado]");
        jPanel1.add(lblServicioSelec, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Mulish Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(34, 52, 64));
        jLabel2.setText("SERVICIO SELECCIONADO:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(lblPerfilUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, 70, 60));

        lblNombreUsu.setFont(new java.awt.Font("Mulish Light", 0, 14)); // NOI18N
        lblNombreUsu.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreUsu.setText("Nombre de usuario");
        lblNombreUsu.setComponentPopupMenu(jpmAcionesUsuario);
        jPanel2.add(lblNombreUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Mulish Black", 1, 23)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Contratar un servicio");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 290, 40));
        jPanel2.add(lblIconoLumina, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 60));
        jPanel2.add(lblDegradado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 80));

        jPanelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jPanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -2, 810, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtNumDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumDocumentoActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
 
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnPaso3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaso3ActionPerformed

    }//GEN-LAST:event_btnPaso3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaContratarServicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaContratarServicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaContratarServicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaContratarServicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaContratarServicio2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPaso3;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> cbTdocumento;
    private javax.swing.JComboBox<String> cb_tPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jPanelFondo;
    private javax.swing.JMenuItem jmiCerrarSesion;
    private javax.swing.JMenuItem jmiEditarPerfil;
    private javax.swing.JPopupMenu jpmAcionesUsuario;
    private javax.swing.JLabel lblCategoriaSelec;
    private javax.swing.JLabel lblDegradado;
    private javax.swing.JLabel lblIconoLumina;
    private javax.swing.JLabel lblNombreUsu;
    private javax.swing.JLabel lblPerfilUsu;
    private javax.swing.JLabel lblServicioSelec;
    private java.awt.TextArea txtAreaDescripcionServicio;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumDocumento;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
